---
booktitle: Proceedings of the Eleventh Symposium on Conformal and Probabilistic Prediction
  with Applications
shortname: COPA
volume: '179'
year: '2022'
start: 2022-08-24
end: 2022-08-26
url: https://proceedings.mlr.press
published: 2022-08-30
location: Brighton, UK
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: COPA-2022
month: 0
cycles: false
bibtex_editor: Johansson, Ulf and Bostr\"{o}m, Henrik and An Nguyen, Khuong and Luo,
  Zhiyuan and Carlsson, Lars
editor:
- given: Ulf
  family: Johansson
- given: Henrik
  family: Boström
- given: Khuong
  family: An Nguyen
- given: Zhiyuan
  family: Luo
- given: Lars
  family: Carlsson
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Eleventh Symposium on Conformal and Probabilistic Prediction with Applications
    Held in Brighton, UK on 24-26 August 2022

  Published as Volume 179 by the Proceedings of Machine Learning Research on 30 August 2022.

  Volume Edited by:
    Ulf Johansson
    Henrik Boström
    Khuong An Nguyen
    Zhiyuan Luo
    Lars Carlsson

  Series Editors:
    Neil D. Lawrence
date_str: 24--26 Aug
author:
  name: PMLR
baseurl: "/v179"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v179
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v179
email: ''
conference:
  name: Conformal and Probabilistic Prediction with Applications
  url:
  location: Brighton, UK
  dates:
  - 2022-08-24
  - 2022-08-25
  - 2022-08-26
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/home/markus/repos/mlresearch/v179/copa22.bib"
# Site settings
# Original source:  /home/markus/repos/mlresearch/v179/copa22.bib
